@startuml

title シーケンス図
/' define participants '/
actor 利用者
actor 担当者
boundary 機器貸出システム
entity 管理マスタ

/' messages '/
opt 予約をしていない時
  利用者 -> 担当者: 予約手続き
end

利用者 -> 担当者: 学生証を渡す

利用者 -> 機器貸出システム: 学籍番号を入力


activate 機器貸出システム
機器貸出システム -> 管理マスタ: 予約情報を取得　
activate 管理マスタ
管理マスタ -> 機器貸出システム: 予約情報を送信
deactivate 管理マスタ
機器貸出システム -> 担当者: 申請情報の表示
activate 担当者
機器貸出システム -> 利用者: 申請情報の表示

note right
  学籍番号
  氏名
  貸出機器名
  貸出開始時刻
  返却時刻
end note

deactivate 機器貸出システム


担当者 -> 担当者: 本人確認
note left
  氏名
  学籍番号
  を学生証を元に確認
end note
担当者 -> 利用者: 確認要求
deactivate 担当者

opt 入力ミスがある時
  利用者 -> 機器貸出システム: 情報の訂正
  activate 機器貸出システム
  機器貸出システム -> 利用者: 申請情報の表示
  deactivate 機器貸出システム
  担当者 -> 利用者: 確認要求
end
担当者 -> 利用者: 機器貸し出し，学生証返却

@enduml