@startuml
actor 利用者
actor 担当者
entity カレンダー
entity 貸出台帳

利用者 -> 担当者: 受付情報伝達
loop [予約なしの時間帯が見つかるまで]
利用者 -> 担当者: 貸出開始，返却時刻伝達
担当者 -> カレンダー: 予約状況取得
カレンダー -> 担当者: 予約状況
担当者 -> 担当者: 予約状況と照合
end
  担当者 -> カレンダー: 入力
  担当者 -> 貸出台帳: 入力
  




@enduml